### PR TITLE
Eslint

### PR DESCRIPTION
**Pull request by abea**

### CODE REVIEW

**Comment by abea** [comment]
@boutell It looks like it's not passing the tests at the moment. I confirmed locally, so not simply a CircleCI thing.

**Comment by abea** [comment]
I'll put this up for a merge for the sake of eslint and getting Circle running the tests.

**Review by boutell — APPROVED** [review]

**Comment by boutell** [comment]
npm test passes if I check out my last commit. Something must've been changed in the meaning of the code.

**Comment by boutell** [comment]
yeah, this is probably it:

```
-    } while (curr = Object.getPrototypeOf(curr));
+    } while (curr === Object.getPrototypeOf(curr));
```

**Pull request merged**
